# Generated by Django 2.2.5 on 2020-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('show_timing', models.DateTimeField()),
                ('Tickets_available', models.IntegerField(default=100)),
                ('Tickets_booked', models.IntegerField(default=0)),
            ],
        ),
    ]
