# Generated by Django 2.2.5 on 2020-03-19 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='show_timing',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='show_timing1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='show_timing2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='show_timing3',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='show_timing4',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
