# Generated by Django 2.2.5 on 2020-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_auto_20200319_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
