# Generated by Django 2.2.5 on 2020-03-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0006_moviedetails_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='trailer',
        ),
    ]
