# Generated by Django 2.2.5 on 2020-03-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0007_remove_moviedetails_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='show_timing3',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='show_timing4',
        ),
    ]
