# Generated by Django 2.2.5 on 2020-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0009_auto_20200323_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='Tickets_current',
        ),
    ]
