# Generated by Django 2.2.5 on 2020-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0010_remove_moviedetails_tickets_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='Tickets_available',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='Tickets_booked',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='Tickets1_available',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='Tickets1_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='Tickets2_available',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='Tickets2_booked',
            field=models.IntegerField(default=0),
        ),
    ]
