# Generated by Django 2.2.5 on 2020-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0011_auto_20200324_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetails',
            old_name='Tickets2_available',
            new_name='Tickets_available',
        ),
        migrations.RenameField(
            model_name='moviedetails',
            old_name='Tickets1_booked',
            new_name='Tickets_booked',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='Tickets1_available',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='Tickets2_booked',
        ),
    ]
